import { FaArrowRightArrowLeft, FaLock } from 'react-icons/fa6';
import { FaBrain } from 'react-icons/fa';
import { MdOutlineShield } from 'react-icons/md';
import { OilType, PlatformFeature, MarketData } from '@/types';

export const features: OilType[] = [
  {
    id: 1,
    title: 'Brent crude oil',
    desc: 'The global benchmark for crude oil',
    icon: '/assets/chart.png',
  },
  {
    id: 2,
    title: 'West Texas Intermediate',
    desc: 'Premium light sweet crude oil',
    icon: '/assets/drum.png',
  },
  {
    id: 3,
    title: 'Dubai Crude',
    desc: 'Middle Eastern crude oil benchmark',
    icon: '/assets/drum.png',
  },
  {
    id: 4,
    title: 'OPEC Basket',
    desc: 'Weighted average of OPEC crude oils',
    icon: '/assets/chart.png',
  },
];

export const platformFeatures: PlatformFeature[] = [
  {
    id: 1,
    icon: FaArrowRightArrowLeft,
    title: 'Decentralized Trading',
    desc: 'Trade directly with other users without intermediaries, ensuring greater control and efficiency.',
  },
  {
    id: 2,
    icon: FaBrain,
    title: 'AI Forecasting',
    desc: 'Leverage advanced AI algorithms for predictive market analysis and personalized trading strategies.',
  },
  {
    id: 3,
    icon: MdOutlineShield,
    title: 'Secure Wallet',
    desc: 'Safeguard your assets with our integrated secure wallet, designed for web3 security.',
  },
  {
    id: 4,
    icon: FaLock,
    title: 'Transparent Transactions',
    desc: 'Benefit from the transparency of blockchain technology.',
  },
];

export const marketData: MarketData[] = [
  {
    id: 1,
    location: 'West Texas Intermediate',
    seller: 'Global Energy Ltd.',
    quantity: '3000 barrels',
    icon: '/assets/drum.png',
    price: 75.5,
    currency: 'USD',
    lastUpdated: new Date(),
  },
  {
    id: 2,
    location: 'West Texas Intermediate',
    seller: 'PetroMax Corp.',
    quantity: '3000 barrels',
    icon: '/assets/chart.png',
    price: 75.25,
    currency: 'USD',
    lastUpdated: new Date(),
  },
  {
    id: 3,
    location: 'West Texas Intermediate',
    seller: 'Energy Solutions Inc.',
    quantity: '3000 barrels',
    icon: '/assets/drum.png',
    price: 75.75,
    currency: 'USD',
    lastUpdated: new Date(),
  },
  {
    id: 4,
    location: 'West Texas Intermediate',
    seller: 'Oil Traders LLC',
    quantity: '3000 barrels',
    icon: '/assets/drum.png',
    price: 75.4,
    currency: 'USD',
    lastUpdated: new Date(),
  },
  {
    id: 5,
    location: 'West Texas Intermediate',
    seller: 'Crude Masters Ltd.',
    quantity: '3000 barrels',
    icon: '/assets/chart.png',
    price: 75.6,
    currency: 'USD',
    lastUpdated: new Date(),
  },
  {
    id: 6,
    location: 'Nigeria Light Sweet',
    seller: 'African Oil Co.',
    quantity: '3400 barrels',
    icon: '/assets/drum.png',
    price: 77.2,
    currency: 'USD',
    lastUpdated: new Date(),
  },
  {
    id: 7,
    location: 'Brent Crude',
    seller: 'North Sea Energy',
    quantity: '3000 barrels',
    icon: '/assets/drum.png',
    price: 78.1,
    currency: 'USD',
    lastUpdated: new Date(),
  },
  {
    id: 8,
    location: 'West Texas Intermediate',
    seller: 'Texas Oil Partners',
    quantity: '3000 barrels',
    icon: '/assets/chart.png',
    price: 75.3,
    currency: 'USD',
    lastUpdated: new Date(),
  },
  {
    id: 9,
    location: 'OPEC Basket',
    seller: 'OPEC Trading Co.',
    quantity: '3000 barrels',
    icon: '/assets/drum.png',
    price: 76.8,
    currency: 'USD',
    lastUpdated: new Date(),
  },
  {
    id: 10,
    location: 'Brent Crude',
    seller: 'European Oil Ltd.',
    quantity: '3000 barrels',
    icon: '/assets/drum.png',
    price: 78.25,
    currency: 'USD',
    lastUpdated: new Date(),
  },
  {
    id: 11,
    location: 'Dubai Crude',
    seller: 'Middle East Oil Co.',
    quantity: '3000 barrels',
    icon: '/assets/drum.png',
    price: 76.5,
    currency: 'USD',
    lastUpdated: new Date(),
  },
  {
    id: 12,
    location: 'West Texas Intermediate',
    seller: 'Small Batch Oil',
    quantity: '200 barrels',
    icon: '/assets/chart.png',
    price: 75.45,
    currency: 'USD',
    lastUpdated: new Date(),
  },
];
